### ISSUE TITLE
Not working neither in local game or dedicated server

### ISSUE THREAD

**Issue by thecko** [smallo92/FireplaceItemDestroy#1]
The mod is installed and active, the new "LShit 1-8" appears but always shows "cannot use item with fireplace". Tried with several items (trophies, dandelions, eyes, etc.) either in our dedicated server and in a local game, with and without cheats activated, but always the same message.

**Comment by smallo92** [comment]
Do you have the latest version of BepInEx installed, when testing people who didn't couldn't get it working. That's why the latest version is listed as a dependency. Seems to work fine for me and the 4 people I tested it with in Local Games, Local Hosted server and a Dedicated server.

**Comment by smallo92** [comment]
The only other thing I can think of is the possibility of localisation issues with KeyCodes. Not sure if that's even a thing in Unity though.

**Comment by thecko** [comment]
> Do you have the latest version of BepInEx installed, when testing people who didn't couldn't get it working. That's why the latest version is listed as a dependency. Seems to work fine for me and the 4 people I tested it with in Local Games, Local Hosted server and a Dedicated server.

I have bepinex 5.4.701 (the lastest from r2modman) but I see in githut a 5.4.8 in github.

**Comment by smallo92** [comment]
Nah that is the latest version I was using. It's also possible some other mod is conflicting by overwriting that function I'm hooking into.

**Comment by thecko** [comment]
![image](https://user-images.githubusercontent.com/1039707/109666624-a2550800-7b6f-11eb-967a-14cf34aa69c0.png)
Tried disabling those 2 that could be a problem but still not working :(

**Comment by smallo92** [comment]
I've actually never tried it with r2modman. It's 1am for me, so I'll give that a go tomorrow and hopefully find something. Let me know if you work it out beforehand.

**Comment by thecko** [comment]
get rest, thanks for the quick reply

**Comment by thecko** [comment]
After the last updates (bepinex and yours) it works, thanks :D
